# Generated by Django 5.0.1 on 2024-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_left',
            field=models.IntegerField(default=0),
        ),
    ]
