# Generated by Django 5.0.1 on 2024-01-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_fee_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fee_left',
            new_name='fee_paid',
        ),
    ]
