# Generated by Django 5.0.1 on 2024-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_fee_left_student_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
