# Generated by Django 5.0.1 on 2024-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('NW', 'New'), ('IM', 'In Moderation'), ('PN', 'Proven')], default='NW', max_length=2)),
                ('amount', models.IntegerField()),
                ('payment', models.CharField(choices=[('CD', 'Card'), ('BK', 'Bank'), ('CH', 'Cash')], default='CD', max_length=2)),
                ('organization', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
