# Generated by Django 5.0.1 on 2024-01-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
