# Generated by Django 5.0.1 on 2024-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
